### ISSUE TITLE
3.0.4 causes ionic build fail.

### ISSUE THREAD

**Issue by ChampRay** [asamuzaK/semverParser#4]
After updating my package.json, I got updated to 3.0.4 and now everytime I do ionic build --prod I get this error.

This can be replicated by simply creating an ionic app and installing the 3.0.4 plugin and then running ionic build --prod

```
// My code
import {compareSemVer, isValidSemVer, parseSemVer} from 'semver-parser';

```
Error on command "ionic build --prod"
```
ERROR in main-es2015.1af85b258c6ada2afeae.js from Terser
Unexpected token: punc ()) [main-es2015.1af85b258c6ada2afeae.js:51081,6]
[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:build:production exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
```

My package.json dependencies

`
    "@angular/animations": "^8.2.14",
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@ionic-native/bluetooth-serial": "^5.19.1",
    "@ionic-native/core": "^5.19.1",
    "@ionic-native/device": "^5.19.1",
    "@ionic-native/splash-screen": "^5.19.1",
    "@ionic-native/status-bar": "^5.19.1",
    "@ionic/angular": "^4.11.8",
    "@ionic/storage": "^2.2.0",
    "@sentry/browser": "^5.11.1",
    "angular-animations": "0.0.10",
    "cordova-android": "7.1.4",
    "cordova-plugin-autostart": "^2.3.0",
    "cordova-plugin-background-mode": "^0.7.3",
    "cordova-plugin-bluetooth-serial": "^0.4.7",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-ionic": "^5.4.6",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.1.3",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova.plugins.diagnostic": "^5.0.1",
    "core-js": "^2.6.11",
    "moment": "^2.24.0",
    "moment-duration-format": "^2.3.2",
    "moment-timezone": "^0.5.27",
    "pluralize": "^8.0.0",
    "pusher-js": "^5.0.3",
    "rxjs": "^6.5.4",
    "semver-parser": "^3.0.4",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
`

**Comment by asamuzaK** [comment]
The error is coming from the Terser.
Why don't you check the issue of it first?

Maybe related:
[Unexpected token: punc ()) with comma after last param in func calls · Issue #412 · terser/terser](https://github.com/terser/terser/issues/412)
